### ISSUE TITLE
Quick-Win port Java rules to Apex

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#1]
**[Code Size Rules](http://pmd.sourceforge.net/snapshot/pmd-java/rules/index.html#Code_Size)** 

- [x] **ExcessiveClassLength**: Long Class files are indications that the class may be trying to do too much. Try to break it down, and reduce the size to something manageable.

- [x] **ExcessiveMethodLength:** When methods are excessively long this usually indicates that the method is doing more than itsname/signature might suggest. They also become challenging for others to digest since excessive scrolling causes readers to lose focus.Try to reduce the method length by creating helper methods and removing any copy/pasted code.

- [x] **ExcessiveParameterList:** Methods with numerous parameters are a challenge to maintain, especially if most of them share thesame datatype. These situations usually denote the need for new objects to wrap the numerous parameters.
ExcessiveClassLength: Excessive class file lengths are usually indications that the class may be burdened with excessive responsibilities that could be provided by external classes or functions. In breaking these methodsapart the code becomes more managable and ripe for reuse.

- [x] **StdCyclomaticComplexity:** Complexity directly affects maintenance costs is determined by the number of decision points in a method plus one for the method entry. The decision points include ‘if’, ‘while’, ‘for’, and ‘case labels’ calls. Generally, numbers ranging from 1-4 denote low complexity, 5-7 denote moderate complexity, 8-10 denotehigh complexity, and 11+ is very high complexity.

- [x] **ExcessivePublicCount:** Classes with large numbers of public methods and attributes require disproportionate testing effortssince combinational side effects grow rapidly and increase risk. Refactoring these classes intosmaller ones not only increases testability and reliability but also allows new variations to bedeveloped easily.

- [x] **TooManyFields:** Classes that have too many fields can become unwieldy and could be redesigned to have fewer fields,possibly through grouping related fields in new objects. For example, a class with individual city/state/zip fields could park them within a single Address field.

**[Design (Java)](http://pmd.sourceforge.net/snapshot/pmd-java/rules/index.html#Design)**

- [x] **AvoidDeeplyNestedIfStmts:** Avoid creating deeply nested if-then statements since they are harder to read and error-prone to maintain.

**[Unused Code (Java)](http://pmd.sourceforge.net/snapshot/pmd-java/rules/index.html#Unused_Code)**

- [ ] **UnusedPrivateField:** Detects when a private field is declared and/or assigned a value, but not used.
- [ ] **UnusedLocalVariable:** Detects when a local variable is declared and/or assigned, but not used.
- [ ] **UnusedPrivateMethod:** Unused Private Method detects when a private method is declared but is unused.
- [ ] **UnusedFormalParameter:** Avoid passing parameters to methods or constructors without actually referencing them in the method body.
- [ ] **UnusedModifier:** Fields in interfaces are automatically public static final, and methods are public abstract.Classes or interfaces nested in an interface are automatically public and static (all nested interfaces are automatically static).For historical reasons, modifiers which are implied by the context are accepted by the compiler, but are superfluous.

**[Naming (Java)](http://pmd.sourceforge.net/snapshot/pmd-java/rules/index.html#Naming)**

- [x] **VariableNamingConventions:** A variable naming conventions rule - customize this to your liking. Currently, it checks for final variables that should be fully capitalized and non-final variables that should not include underscores.
- [x] **MethodNamingConventions:** Method names should always begin with a lower case character, and should not contain underscores.
- [x] **ClassNamingConventions:** Class names should always begin with an upper case character.
- [x] **MethodWithSameNameAsEnclosingClass:** Non-constructor methods should not have the same ng conventions indicate a constant. However, the field is not final.

**Comment by anand13s** [comment]
I would suggest we start with simple naming rules. @adangel  has done a great job to get the parser up and running. I'm forking this to try to setup simple naming rules.

**Comment by up2go-rsoesemann** [comment]
@anand13s great idea and awesome that your are joining the active contributors. I already added a basic rule in commit https://github.com/Up2Go/pmd/commit/03f10491bf97a11844e43418c5dfc34a1c16fa8a.

**Comment by up2go-rsoesemann** [comment]
@adangel I'm having a hard time understanding the PMD testing framework. I understand that its going to make rule test way easier. But where do I need to configure what and where do I defined the input?

Could you have a look at commit https://github.com/Up2Go/pmd/commit/03f10491bf97a11844e43418c5dfc34a1c16fa8a and tell me:

1. If I configured the XML and properties correct
2. How I can apply the rule to the set of [typical Apex classes in the resources](https://github.com/Up2Go/pmd/tree/master/pmd-apex/src/test/resources) folder?

**Comment by up2go-rsoesemann** [comment]
@adangel I found out that PMD is using XMLs to define test source code and success/failure expectations and commited such an XML for my first rule here: https://github.com/Up2Go/pmd/commit/18da883596ef784b40754f1a6ec655e22939def8.

But it still seems not to find the code.

**Comment by adangel** [comment]
I think you basically figured it out already. We usually use complete source code only for parser tests - like you did know with [ApexParserTest](https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ApexParserTest.java#L49). Loading the file and get it parsed. Sometimes, it's enough to see, that the parser didn't crash, sometimes it's necessary to validate, that the parse tree is correct.

For the rules, yes, you already set it up correctly: [BasicRulesTest](https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/basic/BasicRulesTest.java)
*  Extend the base class "SimpleAggregatorTst"
* override "setUp" and configure the rules to test.

The test framework searches now by convention for the XML files, which describe the test cases. It is the "xml" sub-directory of the test class' directory and the name is the rule name, used by the "addRule" call.
In your case, it found already [ConsistentReturn.xml](https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/basic/xml/ConsistentReturn.xml)
and tried to execute the test cases: 3 from 6 pass.

2 tests fail, because PMD doesn't know yet all AST node classes like `VariableDeclarationStatements`, `IfElseBlockStatement`. So - like you said in the last commit "I guess we need more AST nodes..."

The last test ("Bad, mixed result with nested function") fails, because the apex parse didn't return a root node (e.g. there is no UserClass in the file). I've seen this previously and reason was, that the apex compiler couldn't parse it because of a missing curly bracket. In this case, it doesn't seem to be a missing bracket. I'd suggest to copy paste the snippet and let apex try to compile it outside of PMD to make sure, the syntax is valid.

For the xml format of the test cases, I don't think there is a good documentation, but here is some (more complete) example:

    <?xml version="1.0" encoding="UTF-8"?>
    <test-data>
        
        <test-code reinitializeRule="true" regressionTest="true"> 
            <description>Just a description, will be used as the test name for JUnit</description>
            <rule-property name="somePropName">propValue</rule-property> 
            <expected-problems>2</expected-problems>
    
            
            <expected-linenumbers>5,14</expected-linenumbers>
    
            
            <expected-messages>
                <message>Violation message 1</message>
                <message>Violation message 2</message>
            </expected-messages>
    
            <code><![CDATA[
    public class ConsistentReturn {
        public Boolean foo() {
        }
    }
         ]]></code>
            <source-type>apex</source-type>
        </test-code>
    
        
        <code-fragment id="codeSnippet1"><![CDATA[
    public class ConsistentReturn {
        public Boolean foo() {
        }
    }
        ]]></code-fragment>
        
        <test-code>
            <description>description</description>
            <expected-problems>0</expected-problems>
            <code-ref id="codeSnippet1"/>
        </test-code>
    </test-data>


Btw. - I pushed reverts of two commits - these were deleting most of the other modules. So, in case we simply merge this branch back to master, we won't be suprised... (see https://github.com/Up2Go/pmd/commit/e240a024d656899c648c3998f13ee39a433882a8 and https://github.com/Up2Go/pmd/commit/ce3727e10a8b95863662f02a6d4dcc0b45f674cc).

**Comment by up2go-rsoesemann** [comment]
@chalemic I think all the unusedcode rules (see first issue post) are very useful and some of them should be easy to implement

**Comment by up2go-rsoesemann** [comment]
@anand13s In case you didn't already start working on porting the naming rules I just started porting them as part of this commit https://github.com/Up2Go/pmd/commit/523dcc8fe02d7279c917eb003bc0d93c1946b0e6

**Comment by up2go-rsoesemann** [comment]
@anand13s As you see we were successful to port a rich set of the Original Java rules without deep knowledge of the AST produced by you parser.

I would love to add some of the unused code rules but I just weren't able to find the class counterparts in Jorje. Would you be able to do that or at help with which objects are close to their Java counterparts?

**Comment by up2go-rsoesemann** [comment]
All rules checked above are ported and their tests run green. When applying them to real world code we experienced several problems. We will create single issues per problem so we can better work on them.
