### ISSUE TITLE
Should we provide Github-based Maven-repo of Jorje jars

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#18]
@vazexqi @adangel 

I just read [this article about using a GitHub repo as Maven repository](http://kwebble.com/blog/2014/02/19/use-github-to-host-your-own-maven-repo). Do you think we should use that for the Salesforce.com parser libs until Salesforce.com provides their own?

We could then provide a newer version of Jorje by simply changing a jar in our own repo without pull request to pmd/pmd.

Or is it perfectly ok to have them as packaged lib as we have it now?

**Comment by adangel** [comment]
For now, this doesn't matter (custom repo vs. system dependency).

For the longer term, I hope, that the Jorje jar is available in maven central.

Regarding "newer version ... without a pull request": You'll depend on a specific version. Whenever you'll want to change the version, you'll change the dependency and so you change the program. It must be a pull request - otherwise you would build PMD again and get a different result (as the dependency has been changed "under the hood"). This behavior is only valid for SNAPSHOT dependencies but not for releases. This also means - as soon as pmd / pmd-apex shall be released, the Jorje parser library needs to be available as a released version.

**Comment by up2go-rsoesemann** [comment]
@adangel We have no idea when and Salesforce.com (right @vazexqi ?!) is not going to tell us when they releases (and Maven publish) a non-snapshot version of their parser.

We also don't want to wait with pull-requesting and getting the community involved.

What would be the problem, with have a parser which is perfectly working for us under the hoods of our Apex module and just replacing it when and only when Salesforce.com provides major improvements?

**Comment by vazexqi** [comment]
At this point, we cannot give a definite timeline on when the non-snapshot version of the jars are going to be ready. I'm also trying to understand why this is a blocker for proceeding. Imagine, if the official jars are only going to be released next year, or the year after, or the year after next. Should this project be blocked waiting on that?

**Comment by up2go-rsoesemann** [comment]
@vazexqi the problem with SNAPSHOT versions is not a restriction by PMD or @adangel. It's a Maven restriction. If we pull in your jar via pom.xml from a remote repo (e.g. one hosted here) the Maven Central site (which caches and verifies dependencies) would disallow the download.

BUT as we currently do not plan to pull you parser (we just leave it as jar in the repo) there is no problem. ;-)

To make a local bundled jar work with the rest of PMD @adangel has to do some adjustments, but is working on it. We currently plan to pull request our fork back to the trunk next week.
