### ISSUE TITLE
How to handle @SuppressWarnings annotations?

### ISSUE THREAD

**Issue by Up2Go-DavidRenz** [Up2Go/pmd#19]
The Java module of PMD uses the **@SuppressWarnings** to tell PMD if it should ignore some code in some rules, like **@SuppressWarnings("PMD.StdCyclomaticComplexity")**.

This annotation does not exist in Apex, but the parser handles it as annotation as annotation node unless you add a parameter, then it will parse the annotation as method with the name SuppressWarnings().

@adangel Any idea how we can handle this ?

**Comment by adangel** [comment]
The @SuppressWarnings way is available in Java - I don't know, if Apex has a similar annotation, that could be used for this purpose. Originally SuppressWarnings was for the java-compiler itself, but it is generic enough (it takes a String) to be used by other tools, such as PMD.

This is not the only way, to manage suppressions: See http://pmd.github.io/pmd-5.4.1/usage/suppressing.html

The annotation way is of course only available for Java. Other languages can use the "// NOPMD" marker way - although not all languages have it implemented. It is available, if the parses returns a filled map in the method `getSuppressMap()`. It requires to have access to the comments of the source code, as "// NOPMD" is a source-comment. Not sure if the apex parser keeps the comments.


The other two suppress options (by regex, by xpath) work for all languages, but can only use the existing nodes in the tree.

**Comment by up2go-rsoesemann** [comment]
@vazexqi How does Jorje handle comments? Are they accessible in the AST so we could use them to supress PMD rule application like @adangel suggests?

**Comment by vazexqi** [comment]
Hmmm, comments are currently not accessible in the AST. In fact, even during parsing, they are put into a separate channel and are ignored pretty much for the construction of ASTs.

Exposing them to the ASTs, would require massive changes to Jorje's frontend.

> This annotation does not exist in Apex, but the parser handles it as annotation as annotation node unless you add a parameter, then it will parse the annotation as method with the name SuppressWarnings().

The problem with the annotation approach is that you won't be able to save the file to the Salesforce server. When you use Jorje "offline" like you do, it doesn't validate the annotations. But when you save to Salesforce server, it does and will reject that Annotation, since it's not a standard one.

There is a possible third approach, that is a bit more messy. Basically you have an external configuration file that says for this type, method, etc, ignore the following rules. While messy, this has the benefit that you can share the configurations without littering your code with all those ignore rules. So you have a way to configure it for all users. Hypothetical example:

```
<ignore>
  <configuration>
  <type>
     <include>
     MyClass*
     </include>
  </type>
  <rules>
    <rule>TooManyParameters</rule>
  </rules>
  </configuration>
</ignore>
```

FindBugs calls them [filter files](http://findbugs.sourceforge.net/manual/filter.html). Does PMD have something similar?

**Comment by up2go-rsoesemann** [comment]
@adangel I guess there is nothing like that in PMD.

**Comment by up2go-rsoesemann** [comment]
@adangel I regard your "answer" as a yes. ;-) And close this issue.
