### ISSUE TITLE
What AST Root node should we use

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#3]
@vazexqi Which **AST node should we use as root type** :PMD rules (visitors) work on AST root nodes. 
`apex.jorje.semantic.ast.compilation.UserClass` seems to be a good match.

**Comment by vazexqi** [comment]
1. Yes, this can be a real problem. There are ways to code around it locally (use system paths, install locally, etc). But I'm not sure how you would be able to build/package this thing easily. For now, why don't you try https://devcenter.heroku.com/articles/local-maven-dependencies. This might be something to check with the maintainer of PMD for advice.
1. (See the below for more context). The root node is `Compilation`. You would do something like https://github.com/forcedotcom/idecore/blob/master/com.salesforce.ide.ui.editors/src/com/salesforce/ide/ui/editors/apex/outline/OutlineViewVisitor.java. Make sure to store the **first** node of those type (`UserClass`, `UserEnum`, `UserInterface`) that you find since that will be the toplevel. **Subsequent** nodes of those kinds will be inner classes, inner enums, inner interfaces. You want to return `true` in your visit methods to allow you to visit the children.
1. There are four subclasses of `Compilation`: `UserClass`, `UserEnum`, `UserInterface`, `AnonymousClass`. You can ignore `AnonymousClass` since it's unlikely you want to rules on anonymous blocks – they are shortlived and no one persists the source into version control.

**Comment by up2go-rsoesemann** [comment]
We take `apex.jorje.semantic.ast.compilation.UserClass` as this is the only relevant type of code for static code analysis.

**Comment by adangel** [comment]
Just for comparison - in the Java part, we use an AST node called "CompilationUnit" as the root - sounds like "Compilation" of apex. In Java, only one top-level public class is allowed per file/compilation unit and multiple top-level non-public classes. Inner classes are no problem, as they are children of some "top-level" node - however, in case you want to distinguish between inner and top-level classes, you would check the parent node.

Another important detail is, that you'll need to mark the root node class with the [RootNode](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/RootNode.java) interface - without this, XPath-based rules won't work with that language. I think, multiple root nodes would be no problem.
