### ISSUE TITLE
AvoidGlobalModifierRule seems to recognize only classes and void methods

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#34]
Methods with a return are ignored
<img width="675" alt="bildschirmfoto 2016-04-19 um 09 35 00" src="https://cloud.githubusercontent.com/assets/8180281/14631123/2cb9905c-0612-11e6-8fcb-4105a99766ae.png">

**Comment by Up2Go-DavidRenz** [comment]
@up2go-rsoesemann 
The AvoidGlobalModifierRule **only recognize global classes and interfaces**.
I think it is not absolutely important that we don't flag global methods because ["If you declare a method or variable as global, you must also declare the class that contains it as global."](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_access_modifiers.htm)
I guess the single violation at the class declaration is perfectly good.

**Comment by Up2Go-DavidRenz** [comment]
The same applies to **inner classes** and **inner interfaces**

![bildschirmfoto 2016-04-19 um 13 01 29](https://cloud.githubusercontent.com/assets/8180433/14637021/16013690-062f-11e6-8a16-4d81fe2a651e.png)
