### ISSUE TITLE
How to manage dependancy to external parser jar with Maven pom.xml?

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#4]
@adangel I hope it is ok to cite you from a forked PMD repo. 

As you know from my other questions were are working on [a PMD module for the Salesforce.com language Apex](https://github.com/Up2Go/pmd/tree/master/pmd-apex). The company Salesforce.com is currently shipping an ANTLR based parser as part of [their open sourced Eclipse IDE](https://github.com/forcedotcom/idecore). With every new language update they release a new version of that parser and make it [available as jars in this repo](https://github.com/forcedotcom/idecore/tree/master/com.salesforce.ide.apex.core/lib).

We are no Maven experts and don't know how to manage such a dependency via Maven's pom.xml as this jar is not in an open maven repository. It might be the best to let Maven download it from the IDE repo. 

Please advise.

**Comment by adangel** [comment]
There is indeed a possibility, to do this in maven: Download the jar and commit it, e.g. in the local subfolder `lib`. Then add a system-scope-dependency to the pom:

        <dependency>
            <groupId>com.salesforce.ide.apex</groupId>
            <artifactId>apex-jorje-ide</artifactId>
            <version>1.0-sfdc-187-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>${basedir}/lib/apex-jorje-ide-1.0-sfdc-187-SNAPSHOT.jar</systemPath>
        </dependency>

However, **this should only be a temporary solution** to get you going.

Longer term, the dependency has to go into maven central. For open-source projects,
there is [OSS Repository Hosting Guide](http://central.sonatype.org/pages/ossrh-guide.html) by Sonatype, which provides the service for free.
So, maybe Salesforce.com can setup this process.
It's not necessarily to release right away, you also get a public SNAPSHOT repository, from which PMD could download the dependency then as a snapshot until it's ready. However, in order to release a version of PMD which includes apex, this snapshot dependency would need to be released first.

**Comment by up2go-rsoesemann** [comment]
FYI: @vazexqi as proposed by @adangel I will add the dependent libs to the PMD libs folder. 

Nonetheless do you have hosting reusable files like your parser in a central repository for Maven built projects on you roadmap?

**Comment by vazexqi** [comment]
Hosting into a Maven repository is a goal but we don't have a definite timeline yet.
We have hosted several other maven projects (http://mvnrepository.com/artifact/com.force.api) in public repositories so it's something that can be done. It's just a matter of when and I don't have the details on that yet.

**Comment by up2go-rsoesemann** [comment]
@vazexqi @adangel I just read [this article about using a GitHub repo as Maven repository](http://kwebble.com/blog/2014/02/19/use-github-to-host-your-own-maven-repo). Do you think we should use that for the Saelsforce parser libs until Salesforce.com provides their own?

Or is it perfectly ok to have them as packaged lib as we have it now?
