### ISSUE TITLE
Struggle with child parsing the Javascript way?

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#6]
@adangel I made a copy of the Ecmascript module and tried to adapt it for Apex. As I am not a Java programmer and struggle to understand the heavy use of generics in your Adapter code I don't know how to cope with the compile error in 

https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java#L84

where child nodes are visited. I added a minimal rule test to see fi the parser works.

https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ApexParserTest.java

Maybe you can have a short look over the code and see if we got the adaption of the Ecmascript module right?

**Comment by adangel** [comment]
First of all, I think, there are two things missing:
1. missing jar for e.g. `apex.jorje.semantic.tester.EmptySymbolProvider`:

         <dependency>
            <groupId>com.salesforce.ide.apex</groupId>
            <artifactId>apex-jorje-sematic-tests</artifactId>
            <version>1.0-sfdc-187-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>${basedir}/lib/apex-jorje-semantic-1.0-sfdc-187-SNAPSHOT-tests.jar</systemPath>
        </dependency>


2. your code uses java8, PMD uses at the moment java7. In order to override the version, you'll need to set the java.version property in the pom.xml file (in section `properties`):

     &lt;java.version>1.8&lt;/java.version>

Now the problematic [line](https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java#L86):

    astNode.visit(this); // TODO

It doesn't compile, because the method `visit` doesn't exist. I think, the method you want to execute is called: `traverse` - the line should be

    astNode.traverse(this, null);

Not sure about the second parameter, but I assume it is optional - seems to be an additional parameter that can be passed to the visitor.

Next - you would need to override the specific vistor methods from AstVisitor - the one in [line 93](https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java#L93) is not such a method. The visitor from Apex looks different than the one from Ecmascript. The methods for Apex look like:

    public boolean visit(UserClass node, T scope) {
        return defaultVisit();
    }

Seems like you would need to override the visit method for each AST type - I didn't see a generic visit method for all types (e.g. visit(AstNode node, T scope)).
After fixing this, you'll discover, that you still need more dependencies -> when running the tests: "java.lang.NoClassDefFoundError: org/antlr/runtime/RecognitionException".

By the way, you can compile and test the code by running `mvn clean install` on the command in within the `pmd-apex` directory.

**Comment by up2go-rsoesemann** [comment]
Thanks @adangel for your hints. [I extended the pom.xml accordingly](https://github.com/Up2Go/pmd/commit/ea1eca008001ac0bffd171e5c1a20ef15c70a8b7).

Maybe @vazexqi can help on both questions:

 1.**How to correctly visit child nodes from the AST root**

    astNode.traverse(this, null);

in https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java#L84

 2. **What is missing in my adapter classes to call Jorje Visitors?**

**Comment by vazexqi** [comment]
There's lots of threads floating around in my inbox so I hope to answer all of them there.

1. @up2go-rsoesemann - Please take a look at the lib folder in https://github.com/vazexqi/ApexJorjeExample/tree/master/BasicParsing/lib. I just realized that folder was _not_ there earlier because I had told git to ignore .jars in my .gitignore. Apologies for the confusion. These are the minimal jars you need on your classpath to compile/run.
1. We might have a problem with the Java 8 dependency. Jorje uses the new libraries e.g., Optional and new constructs, e.g., lambdas in Java 8. If PMD only allows Java 7, then we would have a  compatibility issue. Do you know when PMD will be updated to Java 8? Is there already a Java 8 branch that we can try?
1. Assume that your AST root, astNode, is a subclass of `Compilation`. Then you can do astNode.traverse(visitor, aScope) where aScope is an instance of `Scope`. `Scope` is used as a stack to keep track of information as you go up and down the tree. It's useful when you enter (push) into a new node and want to keep information for that node until you exit (pop) from that node. You are likely to need this when you do complex analysis.

Action items:

1. Can you create the necessary libs from the lib folder? Note that only apex-jorje-* need to be in your local m2 folder. The other ones (like antlr, axis, etc) have proper maven coordinates.
1. Check in what you have after you have done step #1 above and then I can take a closer look if you still have issues. What @adangel said should help you get started.

**Comment by up2go-rsoesemann** [comment]
@vazexqi I appreciate your quick answers and hope that the threads coming from me are now centralised as issues in this repo...

 1. As @adangel suggested I added all the missing dependencies to the `pom.xml`. Only the only apex-jorje-* are left in the libs folder. I will try to understand and implement what you answered for **3.**

2. @adangel Is there a Java8 version of PMD on the roadmap? There is a java8 module in the repo. Could we work from there or how else can we use Salesforce.com Java8 parser inside PMD ?

**Comment by adangel** [comment]
Java 8: Just override the java version via the maven property `<java.version>1.8</java.version>` in the pom.xml file. The java8 module you see is just for integration tests (PMD can analyze java8 code even if it uses java7). PMD itself is java8 ready (meaning it compiles and works with java8), but I don't have concrete plans yet, when I do the switch - this switch would have impact to all other downstream tools (maven, gradle, ant, etc.).

**Comment by up2go-rsoesemann** [comment]
@vazexqi PMD works perfect with Java 8. I modified the pom.xml accordingly.

**Comment by adangel** [comment]
I didn't decide yet, when to switch to java8. But right now, I see two options:
1. Switch PMD completely - means PMD 5.5.0 would require at least java8 as runtime (5.3.x is java6, 5.4.x is java7, 5.5.x would be java8) which would make sense.
2. Keep PMD at java7, but only require java8 for pmd-apex. Not sure, whether that's possible. Ideally, a useful error message would be displayed if someone tries to analyze apex with java7.

**Comment by vazexqi** [comment]
@up2go-rsoesemann: Just checking in. Are you blocked on anything? Do you need from me or @anand13s?

**Comment by up2go-rsoesemann** [comment]
Yes Nick could you please help me get the adapter working. I took the
Ecmascript module and tried to adapt it to apex.. But I am stuck as I don't
get how all the visiting stuff is working.

See @adangel comments. :-(

Am Donnerstag, 17. März 2016 schrieb Nick Chen :

**Comment by up2go-rsoesemann** [comment]
Forgot to mention you @vazexqi

**Comment by up2go-rsoesemann** [comment]
@adangel Thank you so much for your awesome support getting this closed by adding the missing pieces yesterday. Next time I visit my parents in Munich I owe you a beer.

Please stay tuned, as new questions are on their way ;-)
